<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Erp.Core\Erp.Core.csproj" />
    <ProjectReference Include="..\Erp.Infrastructure\Erp.Infrastructure.csproj" />
    <ProjectReference Include="..\Erp.Modules.Accounting\Erp.Modules.Accounting.csproj" />
    <ProjectReference Include="..\Erp.Modules.HRM\Erp.Modules.HRM.csproj" />
    <ProjectReference Include="..\Erp.Modules.Inventory\Erp.Modules.Inventory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\Account\" />
  </ItemGroup>

</Project>
